### ISSUE TITLE
Bot is re-reading old messages

### ISSUE THREAD

**Issue by Filnor** [SOBotics/Thunder#6]
I pinged Thunder in SOBotics to check if it's running:
> [@ Thunder alive](https://chat.stackoverflow.com/transcript/message/42769322#42769322)

The Bot replied with:
> [@ Filnor Yes](https://chat.stackoverflow.com/transcript/message/42769325#42769325)

Which is fine so far, but a few minutes later the bot replied to the message again:
> [:42769322 Yes](https://chat.stackoverflow.com/transcript/message/42769491#42769491)

The issue could be related to [Botpy](https://github.com/SOBotics/Botpy), but someone needs to debug to find that out.

**Comment by double-fault** [comment]
Haven't seen this since a long time. If you see it again, please comment or reopen.

**Comment by Filnor** [comment]
Yep, me too.
